### ISSUE TITLE
redis 과금 이슈로 인한 aws redis와 docker-compose사용 

### ISSUE THREAD

**Issue by AhGnuesHo** [a-co-ha/server#38]
[레디스 클라우드 콘솔](https://app.redislabs.com/#/subscriptions/subscription/1969591/bdb)에서 레디스를 생성해서 사용중이었다. 
여기는 한국 리전을 제공하고 있지 않아서 불가피하게 버지니아 리전을 사용하게 되었다. 

클라이언트도 aws 인스턴스를 생성해서 따로 배포해두었는데 버지니아에서 서울로 데이터가 전송되면서 프리티어임에도 요금이 부과되고 있었다. 
 
aws에서 한국리전에서 [redis elasticache](https://ap-northeast-2.console.aws.amazon.com/elasticache/home?region=ap-northeast-2#/redis)를 새로 생성해서 문제를 해결했다. 

aws Redis 클러스터는 ec2 인스턴스 안에서만 연결이 되므로 로컬에서는 접속 할 수 없다. 

그러므로 일단 ec2 인스턴스에서 접속했고, redis를 설치했다. 
```
$ wget http://download.redis.io/redis-stable.tar.gz && tar xvzf redis-stable.tar.gz && cd redis-stable && make
$ sudo cp src/redis-cli /usr/bin
```

```
redis-cli -h [ 엔드포인트 ] p [포트]
```
<img width="921" alt="iShot_2023-03-22_20 17 31" src="https://user-images.githubusercontent.com/69295153/226888592-4a33565e-4b68-4612-9573-5aaa5bc8c92a.png">

이렇게 ec2 안에서 redis 접속을 확인 할 수 있다. 

___

이제 express 에서 redis를 연결해야한다. 

이때 docker를 사용했다. 
[docker, docker-compose설치](https://velog.io/@skyepodium/AWS-ubuntu-docker-docker-compose-%EC%84%A4%EC%B9%98)를 먼저 해야한다. 
**`sudo usermod -aG docker $USER` 명령어가 잘 적용이 되지않아 퍼미션 오류가 떴는데 로그아웃 후 다시 접속하니 해결되었다.** 

이후 docker-compose를 작성해서 redis를 실행시켰다. 
```
//docker-compose.redis.yml 

version: "3"
services:
  redis-docker:
    image: redis:latest
    command: redis-server --port 6379
    container_name: "docker-redis"
    ports:
      - 6379:6379
```
`docker-compose -f docker-compose.redis.yml up -d`로 실행 시키고 `docker ps`로 다음과 같이 실행됨을 확인 할 수 있다.
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/69295153/226892277-b7d614f8-6b9f-4265-8595-0faf551332f3.png">

그리고 redis-connect하는 부분에서 host부분을 redis엔드포인트로 적용해주면 된다.
