### ISSUE TITLE
redis host문제

### ISSUE THREAD

**Issue by AhGnuesHo** [a-co-ha/server#43]
aws redis cache를 생성하고 ec2컨테이너 안에서 도커 컴포즈로 nginx, redis, express를 각각 띄워 배포를 진행했다. 

redis에 세션이 저장되도록 했는데 
<img width="550" alt="iShot_2023-03-30_14 57 17" src="https://user-images.githubusercontent.com/69295153/228743601-52d50d95-64f9-4f20-924d-e1cf80e15ab9.png">
위와 같이 redis host로 접속해서 키를 확인해보니 아무런 값이 저장되어있지 않았다. 

세션은 아래와 같이 ec2 로컬에 저장되고 있었다. 
host를 바꿔야한다. 
<img width="424" alt="iShot_2023-03-30_14 57 03" src="https://user-images.githubusercontent.com/69295153/228743786-ee12fe5e-fb29-44b7-897c-d62fb63d6fe8.png">

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/69295153/228743933-9bb7cd86-1778-46bc-a79a-0c1332a5ca8e.png">
예상되는 이유는 host를 0.0.0.0으로 다 허용해놔서인가..? 

```js
export const redisClient: any = Promise.promisifyAll(
  redis.createClient({
    socket: {
      host: 'redis-server',
      port: 6379,
    },
    legacyMode: true,
  })
);
```
```yml

  redis-server:
    image: redis:latest
    container_name: "redis"
    command: redis-server --port 6379
    ports:
      - 6379:6379
```
docker-compose 에 r redis-server라고 명시해서 위와 같이 작성했고,   레디스 클라이언트를 만들때  도커 컴포즈에서 명시한  redis-server를 host에 작성해서 사용중이다. 

docker-compose 작성하는 법 알아보기

**Comment by AhGnuesHo** [comment]
이게 원인이 아니었다.

**Comment by AhGnuesHo** [comment]
저렇게 함으로써 외부 접속이 가능한 것은 맞지만 이미 ec2인스턴스 안에서 redis를 설치하고 실행하고 있으므로 도커 컴포즈로 redis를 또 띄울 필요가 없었다. 

즉
![image](https://user-images.githubusercontent.com/69295153/228775073-c19d8b07-9dbb-4665-93eb-109310ef9d55.png)
이건 도커 컴포즈로 실행시킨 redis가 기본으로 conf 파일에서 바인딩 중인 127.0.0.1 호스트로 띄운 것이고 

![image](https://user-images.githubusercontent.com/69295153/228775310-37ff07f9-7cb8-4765-9a61-1a3f2c94eda1.png)
aws rediscache는 그냥 인스턴스에 설치된 redis로 접속했을때 나오는 것이다. 

그리고 당연히 
```
export const redisClient: any = Promise.promisifyAll(
  redis.createClient({
    socket: {
      host: 'redis-server',
      port: 6379,
    },
    legacyMode: true,
  })
);```
여기선 도커로 띄운 redis-server 를 호스트로 지정해두었기 때문에 세션이  127.0.0.1 호스트에 저장된 것이었다. 

도커 컴포즈에서 
```yml
  redis-server:
    image: redis:latest
    container_name: "redis"
    command: redis-server --port 6379
    ports:
      - 6379:6379
 ```

이 부분을 지웠다. 

그리고 
<img width="425" alt="image" src="https://user-images.githubusercontent.com/69295153/228776121-fea7cc68-7ea2-4c39-a00f-15a4fb26ae13.png">

이렇게 host를 환경변수에서 꺼내 쓰는 것으로 수정했다. 

도커로 redis를 띄우지 않았으니 
<img width="663" alt="image" src="https://user-images.githubusercontent.com/69295153/228776374-ba957cf1-5a4d-4627-b436-4c164c7e61c7.png">

당연히 로컬로 redis를 접속하려하면 접속이 되지 않는다. 

<img width="565" alt="image" src="https://user-images.githubusercontent.com/69295153/228776858-99214804-c15c-468c-b4dc-34d33cc83471.png">
aws redis cache에 세션이 잘 저장되고 있다!

**Comment by AhGnuesHo** [comment]
보통 도커 컴포즈에서 각종 디비(mongoose, mysql, redis)이미지를 각각 생성하고 한꺼번에 띄우는 것으로 알고 있다. 

하지만 중간에 도커를 도입하다보니 이런 점에서 인지 오류가 생긴것 같다 하하

우분투에서 도커를 실행하지 않고 도커 컴포즈 옵션들을 사용해 레디스를 실행한 후 aws 외부 서버로 접속하는 방법도 분명 있을 것이다 이건 나중에 알아보자

**Comment by AhGnuesHo** [comment]
redis에 키가 사라지고 backup1,2,3,4라는 것이 계속 생기고 있었다
데이터가 자꾸 날라가는 이유를 찾아보다가 모니터링을 해보니 flushall로 모든 데이터를 지우고, backup1,2,3,4로 덮어 씌우고 있었다. 

이유는 기본포트 6379와 패스워드가 제대로 설정되지 않아 크롤러 봇들에게 해킹을 당한것이었다. 

```
  redis-server:
    image: redis:latest
    container_name: "redis"
    command: redis-server /usr/local/conf/redis.conf
    ports:
      - 6379:6379
    volumes:
       - ./data/:/data
       - ./conf/redis.conf:/usr/local/conf/redis.conf

```

redis 패스워드를 지정한 설정파일을 볼륨에 지정해주었다.
<img width="428" alt="iShot_2023-04-14_16 42 57" src="https://user-images.githubusercontent.com/69295153/231979487-f0337a14-e6cd-4fb9-93cc-92a940131763.png">


그리고 도커 컴포즈를 다시 시작하고 keys * 를 확인하면 conf에 지정한 패스워드를 작성하라고 나온다. 
이제 봇들에 의한 해킹을 방지할 수 있게되었다.
